USE MY_DATABASE;
SELECT * FROM mytable LIMIT 5;
-- BUSINESS PROBLEMS...............

 -- 1. TOTAL REVENUE GENERATED BY MALE VS FEMALE CANDIDATE.?
 select gender , sum(purchase_amount) from mytable 
 group by gender ;
 -- ans -> male more female less 
 
 -- 2 which customer used discount but still spent more than average purchase amount ? 
 select customer_id , purchase_amount  
 from mytable 
 where discount_applied = 'yes' and purchase_amount > (select avg(purchase_amount) from mytable);
 
 -- 3 top 5 product with highest average review rating ??
 select item_purchased , round(avg(review_rating),2) from mytable
 group by item_purchased 
 order by round(avg(review_rating),2) desc
 limit 5 ;
 
 -- 4 compare average purchase_amount between standard and express shiping?
 select round( avg( purchase_amount ),2) as avg_purchase_amt , shipping_type from mytable
 where shipping_type in ('standard' , 'express')
 group by shipping_type;
 
 -- 5 do subscribe customer spend more? compare average_spend and total revenue between subscriber 
 -- and non subscriber
 select subscription_status , count(customer_id) as total_customer  , 
 round(avg(purchase_amount),2) as avg_spend , sum(purchase_amount) as total_revenue
 from mytable
 group by subscription_status 
 order by avg_spend , total_revenue desc;
 
 -- 6 which 5 products have highest percentage of purchases with discount applied ?
 
 select item_purchased ,
 round(
 count(case when discount_applied = 'yes' then 1 end) /count(*)*100,
 2 ) as discount_rate
 from mytable 
 group by item_purchased 
 order by discount_rate desc 
 limit 5;
 
 -- 7. segment customer into new , returning and loyal based on their total no. of previous purchases
 with customer_type as
 (
 select previous_purchases , customer_id , 
 case when previous_purchases = 1 then 'new'
 when previous_purchases between 2 and 15 then 'returning'
 else 'loyal'
end as customer_segment
from mytable
)
select customer_segment ,count(*) as no_of_customer
from customer_type
group by customer_segment;

-- 8 3 top most purchased products within each category 
with item_count as (
select category , item_purchased ,
count(customer_id) as total_orders , 
Row_number()over( partition by  category order by count(customer_id) desc) as item_rank
from mytable
GROUP BY CATEGORY, ITEM_PURCHASED
)
SELECT ITEM_RANK , CATEGORY , ITEM_PURCHASED , TOTAL_ORDERS
FROM ITEM_COUNT
WHERE ITEM_RANK <=3;

-- 9 ARE CUSTOMERS WHO ARE REPEAT BUYERS (MORE THAN 5 PREVIOUS PURCHASES) ALSO LIKELY TO SUBSCRIBE?
SELECT  subscription_status ,
 COUNT(customer_id) as repeat_buyers
 FROM MYTABLE
WHERE previous_purchases > 5 
group by subscription_status ;

-- 10 what is the revenue_contribution of each age_group
select age_group,sum(purchase_amount) as revenue_contribution
from mytable 
group by age_group
order by revenue_contribution desc;


ALTER USER 'root'@'localhost' 
IDENTIFIED WITH mysql_native_password
BY 'YourNewPassword';

flush privileges
